name: e2e-sample-ios

on:
  pull_request:
    branches:
      - develop
      - master
    types: [opened, synchronize]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        id: installDeps
        run: yarn --frozen-lockfile && yarn bootstrap-ci
      - name: Install node_modules retry
        if: failure() && steps.installDeps.outcome == 'failure'
        run: yarn --frozen-lockfile && yarn bootstrap-ci

      - name: Install Pods
        run: cd ./examples/SampleApp && npx pod-install
      - name: Install Detox Dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Build
        run: yarn detox-sample-ios:build

      - name: Test
        id: detoxRun
        # Sudo is needed to run offline tests
        # -E should only pass secrets if theyre exposed to the job through ENV param
        run: sudo -E npx detox test --configuration ios.sample.release e2e/entries/SampleApp.e2e.js --record-logs failing --record-videos failing

      - uses: actions/upload-artifact@v2
        if: failure() && steps.detoxRun.outcome == 'failure'
        with:
          name: detox-artifacts
          path: ./artifacts
