name: e2e-sample-android

on:
  pull_request:
    branches:
      - develop
      - master
      - v4
    types: [opened, synchronize]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: yarn --frozen-lockfile && yarn bootstrap-ci

      - name: Use specific Java version for sdkmanager to work
        uses: joschi/setup-jdk@v2
        with:
          java-version: 'openjdk8'
          architecture: 'x64'

      - name: Build Android App
        id: buildApp
        run: yarn detox-sample-android:build

      - name: Build Android App retry
        if: failure() && steps.buildApp.outcome == 'failure'
        run: yarn detox-sample-android:build

      - name: Download Android Emulator Image
        run: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-29;default;x86_64"
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd --force --name Pixel_29_AOSP -d pixel -k 'system-images;android-29;default;x86_64'
          $ANDROID_HOME/emulator/emulator -list-avds

      - name: Launch Emulator
        continue-on-error: true
        timeout-minutes: 3
        run: |
          echo "Starting emulator"
          nohup $ANDROID_HOME/emulator/emulator -avd Pixel_29_AOSP -cores 2 -memory 6000 -gpu host -no-audio -no-snapshot -no-window &

      - name: Emulator Status Check
        id: emu1Check
        continue-on-error: true
        timeout-minutes: 3
        run: |
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'

      - name: Launch Emulator Rety
        timeout-minutes: 3
        continue-on-error: true
        if: failure() && steps.emu1Check.outcome == 'failure'
        run: |
          echo "Starting emulator, second attempt"
          $ANDROID_HOME/platform-tools/adb devices
          sudo killall -9 emulator-5554 || true
          sleep 2
          nohup $ANDROID_HOME/emulator/emulator -avd Pixel_29_AOSP -cores 2 -memory 6000 -gpu host -no-audio -no-snapshot -no-window &

      - name: Emulator Status Check 2
        continue-on-error: true
        timeout-minutes: 3
        if: failure() && steps.emu1Check.outcome == 'failure'
        run: |
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'

      - name: Test
        id: detoxRun
        # Detox uses Espresso to choreograph steps in reaction to UI events, so we need to send a stream of taps.
        run: |
          $ANDROID_HOME/platform-tools/adb devices
          $ANDROID_HOME/platform-tools/adb shell settings put global window_animation_scale 0.0
          $ANDROID_HOME/platform-tools/adb shell settings put global transition_animation_scale 0.0
          $ANDROID_HOME/platform-tools/adb shell settings put global animator_duration_scale 0.0
          yarn detox-sample-android:test --record-logs failing --record-videos failing

      - uses: actions/upload-artifact@v2
        if: failure() && steps.detoxRun.outcome == 'failure'
        with:
          name: detox-artifacts
          path: ./artifacts
