name: Nightly Release

on:
  push:
    branches:
      - develop
    paths:
      - package

jobs:
  publish-nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare git
        run: |
          git config --global user.name "Stream Chat RN Nightly"
          git config --global user.email "nightly@getstream.io"
          git fetch
          git checkout master
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          cat .npmrc
          echo "npm whoami"
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Installation
        run: yarn
      - name: Publish Nightly release
        run: |
          yarn lerna publish --canary --preid nightly.${GITHUB_SHA::7} --dist-tag nightly --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
